spring:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/primary_db
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver

    secondary:
      url: jdbc:h2:mem:secondary_db
      username: sa
      password: password
      driver-class-name: org.h2.Driver
